### ISSUE TITLE
time not implemented on this platform

### ISSUE THREAD

**Issue by lastmjs** [dfinity/cdk-rs#119]
While trying to run [proptest](https://github.com/AltSysrq/proptest), just the simplest test run, I immediately get the runtime error: `https://github.com/AltSysrq/proptest`.

Seems there are a number of these basic functionalities that the platform or target could provide, time and randomness come to mind. Each time I run into these issues I have to figure out how to fix them in non-elegant ways, it would be nice for them to just work.

**Comment by adamspofford-dfinity** [comment]
Closing, not because this is not a real problem or because it can't be fixed, but because the fix won't arrive in this repo. This is a fundamental part of using `wasm32-unknown-unknown`, and support either for `wasm32-wasi`, or a custom target, is the only way these things can either Just Work or be patched in.
