### ISSUE TITLE
condvar wait not supported

### ISSUE THREAD

**Issue by lastmjs** [dfinity/cdk-rs#174]
Forum post: https://forum.dfinity.org/t/condvar-wait-not-supported/9052

I'm trying to execute cross-canister calls from within a function that I cannot make async. I am using the `futures` crate to do this. `futures::executor::block_on` works just fine if I call my own `async` functions, but when I try to call `ic_cdk::api::call::call` I get this error:

```bash
[Canister rrkah-fqaaa-aaaaa-aaaaq-cai] Panicked at 'condvar wait not supported', library/std/src/sys/wasm/../unsupported/condvar.rs:23:9
```

Here's an example of the call I am trying to make (this is within a function that cannot be made async):

```rust
let string = futures::executor::block_on(async {
    let call_result: Result<(String,), _> = ic_cdk::api::call::call(
        ic_cdk::export::Principal::from_text("ryjl3-tyaaa-aaaaa-aaaba-cai").unwrap(),
        "testString",
        ()
    ).await;

    return call_result.unwrap().0;
});
```

I've narrowed things down to...well, I really think there's an issue in the `ic-cdk` futures implementation somehow. I don't yet understand Rust futures super well, but my own async functions work just fine, so I assume there is an issue with the futures that `ic-cdk` functions are using.

**Comment by lastmjs** [comment]
Also, if https://github.com/dfinity/cdk-rs/issues/7 were resolved, I wouldn't have to use `futures::executor::block_on`. Perhaps that's the best path forward? How hard would it be to change `ic_cdk::block_on` to return the future output value?

**Comment by lastmjs** [comment]
Here's a minimal working (not working) example of what needs to be done: https://github.com/lastmjs/test-ic-boa-async

**Comment by adamspofford-dfinity** [comment]
#189 was meant to close this but did not. Closing.

**Comment by lastmjs** [comment]
The issue has not been resolved, what should I do to continue the discussion? Changing the name of block_on to spawn helped to clarify but did not address the capabilities that are missing

**Comment by adamspofford-dfinity** [comment]
block_on works for futures you create that do not depend on inter-canister calls because they are not actually asynchronous - they never suspend, Future::poll returns Ready every time. The asynchrony occurs when the call must be broken up across multiple function invocations. You fundamentally cannot block on an inter-canister call. Setting aside whether spinlocking on long-running operations will run you past the instruction limit, the 'return' of an inter-canister call comes from the system calling a callback function. In that callback function is where the remainder of the update call is executed. If you could spin forever on the completion of the call, the call would never complete, as it would be waiting for you to stop spinning before calling the callback function. The purpose of async/await is to abstract over such callback-based models so it feels like you are writing blocking code when in reality the segments of the function between await-points are executed in very different places.

**Comment by adamspofford-dfinity** [comment]
In short, there is no answer, you cannot block, turtles the whole way down. You can solve the boa issue by not using raw_rand every time but rather calling it once and using it to seed a CSPRNG, which you can then invoke synchronously.
