### ISSUE TITLE
can we have a repository as IC community? or Dfinity community

### ISSUE THREAD

**Issue by TimGuo7** [dfinity/cdk-rs#177]
I am new here and want to contribute to the development of Dfinity community.
can we have a certain repository like Dfinity community for members like me to publish events or webinars and sharing these infos here. 
understand that's forums and websites or meetup to do so, but I still recommend to have such a repository here on Github.

**Comment by adamspofford-dfinity** [comment]
The correct place for updates and chat, as opposed to code, is the [forum](https://forum.dfinity.org). A GitHub repo would be strictly inferior - there is a reason other projects do not do this. In addition it would require that people need to check another place for the full experience. 

If you disagree, the forum is a great place to have that disagreement too, because this does not really have anything to do with the CDK. Closing for that reason.

**Comment by TimGuo7** [comment]
I thought it could be closed earlier.
