### ISSUE TITLE
`ic-certified-assets`: support for calling `http_request` via `update`, or `http_request_update`

### ISSUE THREAD

**Issue by paulyoung** [dfinity/cdk-rs#310]
I’d like to have a single entry point for all HTTP requests so I can use the same hostname for all canisters.

Since inter-canister query calls aren’t supported, I’m forwarding the request to my assets canister as an update call for now.

However, this traps because no certificate data is available. 

https://github.com/dfinity/sdk/blob/43f200abea7000de1abe6eb7185b73ae3b363ed4/src/canisters/frontend/ic-certified-assets/src/lib.rs#L159-L162

Is this a use-case that could be supported?

I’m currently using `"type": "asset"` in `dfx.json` and would like to keep the convenience of having a separate assets canister. I’m already hitting the Wasm module function limit so need to keep things separate anyway.

**Comment by nomeata** [comment]
> Since inter-canister query calls aren’t supported, I’m forwarding the request to my assets canister as an update call for now.

Not sure how this could work. The initial canister receives a query call, and you can’t call the asset canister from that canister (even if the asset canister would not fail processing that request).

So for now proxying http requests like that is likely not supported.

**Comment by paulyoung** [comment]
I return a response from `http_request` with `upgrade: true` and then make the call in `http_request_update`

**Comment by nomeata** [comment]
Oh, right, I forgot that part.

Ok, then the next question is certification: The code above fails because the asset canister tries to certify the response, and that can only work in a query. One could maybe make it return an uncertified response when called with an update call, but you won’t (easily) be able to certify that in your proxying canister. So this could only work for raw URLs at all.

Hmm, and then on the side of the asset canister we are in a bad spot: It is not at all easy to dynamically detect that you are handling an update call. This was an intentional design decision which kinda made sense while query methods were a strict subset of update methods, but now with certification, query methods can do some things that update methods can’t. Ugh.

**Comment by paulyoung** [comment]
Also, I was hoping to to do the “zero downtime upgrades” approach but this seems to get me into a situation where I might have outstanding responses when trying to upgrade.

**Comment by paulyoung** [comment]
Closing this since the crate has moved repos. I opened https://github.com/dfinity/sdk/issues/2551 to continue discussing things there.
